services:
  authentication-service:
    build: .
    env_file: .env
    ports:
      - "${AUTHENTICATION_SERVICE_APP_PORT}:80"
    depends_on:
      - authentication-service-db
    networks:
      - authentication-service-net
      - backend-net

  authentication-service-db:
    image: mysql:8.0
    container_name: mysql-auth
    ports:
      - "${AUTHENTICATION_SERVICE_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHENTICATION_SERVICE_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${AUTHENTICATION_SERVICE_DATABASE_DB}
      MYSQL_USER: ${AUTHENTICATION_SERVICE_DATABASE_USER}
      MYSQL_PASSWORD: ${AUTHENTICATION_SERVICE_DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authentication-service-net

volumes:
  mysql-data:

networks:
  authentication-service-net:
  backend-net:
    external: true